parser: babel-eslint
extends: airbnb
plugins:
  - flowtype
rules:
  eqeqeq:
    - error
    - allow-null
  no-unused-expressions:
    - error
    - allowShortCircuit: true
  strict: off
  no-use-before-define:
    - error
    - functions: false
  no-multi-spaces:
    - warn
    - exceptions:
        VariableDeclarator: true
        ImportDeclaration: true
  key-spacing:
    - warn
    - 
      beforeColon: false
      afterColon: true
      mode: 'minimum'
